config/routes.rb
Rails.application.routes.draw do

  get 'charges/new'

  resources :charges, only: [:new, :create]

  resources :wikis

  delete 'wikis/:id/collaborations/destroy_multiple' => 'collaborations#destroy_multiple', as: :d_m_collaborations
  post   'wikis/:id/collaborations/create_multiple' => 'collaborations#create_multiple', as: :c_m_collaborations

  devise_for :users
  resources :users, :only => [:show]

  put 'users/:id/downgrade' => 'users#downgrade', as: :user_downgrade 

   
  get 'about' =>  'welcome#about'

  root 'welcome#index'

  

end

app/models/amount.rb
class Amount

  def self.default
    15_00
  end
  
end 

app/models/collaboration.rb
class Collaboration < ActiveRecord::Base
  belongs_to :user
  belongs_to :wiki
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :wikis
  has_many :collaborations
  #has_many :wikis, through: :collaborations

  before_save { self.role ||= :member }

  enum role: [:member, :premium, :admin]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  def avatar_url(size)
  	gravatar_id = Digest::MD5::hexdigest(self.email).downcase
  	"http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
  end       
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborations
  has_many :users, through: :collaborations

  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 20 }, presence: true
  #validates :user, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #before_action :authenticate_user!
  
  protect_from_forgery with: :exception

  include Pundit
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
  	if current_user.present?
      flash[:alert] = "You are not authorized to perform this action."
      redirect_to user_path(current_user)
  	else	
      flash[:alert] = "You need to sign up to perform this action."
      redirect_to(new_user_registration_path)
    end 
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "BigMoney Membership - #{current_user.email}",
      amount: Amount.default
    }
  end

  def create
    # Creates a Stripe Customer object, for associating
    # with the charge
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )
 
    # Where the real magic happens
    charge = Stripe::Charge.create(
      customer: customer.id, # Note -- this is NOT the user_id in your app
      amount: Amount.default,
      description: "BigMoney Membership - #{current_user.email}",
      currency: 'usd'
    )

    User.find(current_user.id).update_attribute(:role, 1)
 
    flash[:notice] = "Thanks for your payment, #{current_user.email}! You have been upgraded to premium member."
    redirect_to root_path # or wherever
 
    # Stripe will send back CardErrors, with friendly messages
    # when something goes wrong.
    # This `rescue block` catches and displays those errors.
    rescue Stripe::CardError => e
      flash[:alert] = e.message
      redirect_to new_charge_path
  end
end    

app/controllers/collaborations_controller.rb
class CollaborationsController < ApplicationController

  def destroy
  	@wiki = Wiki.find(params[:wiki_id])
  	@collaboration = @wiki.collaborations.where(user_id: params[:collaboration][:user_id])

  	if collaboration.destroy
      flash[:notice] = "Collaborator removed."
    else
      flash[:alert] = "Removal failed."
    end
    
    redirect_to edit_wiki_path(@wiki)
  end

  def destroy_multiple
  	@wiki = Wiki.find(params[:id])
  	if Collaboration.destroy(params[:collaborations])
      flash[:notice] = "Collaborator removed."
    else
      flash[:alert] = "Removal failed."
    end
    
    redirect_to edit_wiki_path(@wiki)
  end

  def create
  	@wiki = Wiki.find(params[:wiki_id])
  	@collaboration = @wiki.collaborations.build(collaboration_params)
    #@collaboration = Collaboration.new
    #@collaboration.wiki_id = params[:wiki_id]
    #@collaboration.user_id = params[:user_id]

    if @collaboration.save
      flash[:notice] = "New collaborator was added."
      redirect_to edit_wiki_path(@wiki)
    else  
  # #12
      flash.now[:alert] = "There was an error adding collaborator. Please try again."
      redirect_to [@wiki]
    end
  end

  def create_multiple
  	@wiki = Wiki.find(params[:id])
  	collaborators = params[:collaborators]
    collaborators.each do |collaborator|
      @collaboration = @wiki.collaborations.build(:user_id => collaborator)
      if @collaboration.save
      	flash[:notice] = "New collaborator was added."
      else
        flash.now[:alert] = "There was an error adding collaborator. Please try again."
        break
      end
    end
    redirect_to edit_wiki_path(@wiki)
  end

  private
 
  def collaboration_params
    params.require(:collaboration).permit(:user_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    authorize @user
    session[:return_to] ||= request.referrer
  end

  def downgrade
  	@user = User.find(params[:id])
  	@user.role = 0

    @user.wikis.each do |wiki|
      wiki.update_attribute(:private, false)
    end  

  	if @user.save
      flash[:notice] = "You've been downgraded to a standard user. All your private wikis became public."
      redirect_to @user
    else
      flash.now[:alert] = "Error downgrade your subscription. Please try again."
      redirect_to @user
    end
  end	

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  def index
  	#@wikis = Wiki.all
    @wikis = policy_scope(Wiki)
  end

  def show
  	@wiki = Wiki.find(params[:id])
  end

  def new
  	@wiki = Wiki.new
  end

  def create
  	@wiki = Wiki.new
    authorize @wiki

  	@wiki.title = params[:wiki][:title]
  	@wiki.body = params[:wiki][:body]
    if current_user.premium? || current_user.admin?
      @wiki.private = params[:wiki][:private]
  	else
      @wiki.private = false  
    end
    
    @wiki.user = current_user  

    if @wiki.save
      redirect_to @wiki, notice: "Wiki was saved successfully."
    else
      flash.now[:alert] = "Error creating wiki. Please try again."
      render :new
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    authorize @wiki
 
    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to action: :index
    else
      flash.now[:alert] = "There was an error deleting the wiki."
      render :show
    end
  end	

  def edit
  	@wiki = Wiki.find(params[:id])
    users = User.where.not(id: current_user.id)
    @wiki.users.each do |user|
      users = users.where.not(id: user.id)
    end
    @users = users.where.not(role: 2)
    @collaboration = Collaboration.new
  end

  def update
    @wiki = Wiki.find(params[:id])
    authorize @wiki

    @wiki.title = params[:wiki][:title]
  	@wiki.body = params[:wiki][:body]
    if (@wiki.user.id == current_user.id && current_user.premium?) || current_user.admin?
      @wiki.private = params[:wiki][:private]
    end
 
    if @wiki.save
      flash[:notice] = "Wiki was updated."
      redirect_to @wiki
    else
      flash.now[:alert] = "Error saving wiki. Please try again."
      render :edit
    end
  end	
end

app/helpers/application_helper.rb
require 'redcarpet'

module ApplicationHelper

  def markdown(text)	
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true)
    markdown.render(text).html_safe
  end

end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborations_helper.rb
module CollaborationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper    
end

app/views/charges/new.html.erb
<h1>Charges#new</h1>
<%= form_tag charges_path do %>
<h3>Premium membership upgrade</h3>
  <h4>Click the button!</h4>
  <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" ></script>
<% end %>

app/views/collaborations/_add_collaborators.html.erb
<%= form_tag c_m_collaborations_path, method: :post do %> 
  <ul class="user-list">
    <% users.each do |user| %>
        <li><%= check_box_tag "collaborators[]", user.id %><%= user.email %></li>
    <% end %>  
  </ul>  
  <%= submit_tag "Add collaborator" %>
<% end %>

app/views/collaborations/_collaborators.html.erb
<%= form_tag d_m_collaborations_path, method: :delete do %> 
  <ul class="user-list">
    <% wiki.collaborations.each do |collaboration| %>
      <li><%= check_box_tag "collaborations[]", collaboration.id %><%= wiki.users.find(collaboration.user_id).email %></li>
    <% end %>  
  </ul>  
  <%= submit_tag "Remove collaborator" %>
<% end %>
 

app/views/collaborations/edit.html.erb
<h1>Collaborations#edit</h1>
<p>Find me in app/views/collaborations/edit.html.erb</p>

app/views/collaborations/show.html.erb
<h1>Collaborations#show</h1>
<p>Find me in app/views/collaborations/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <ul class="nav nav-tabs">
    <li><%= link_to "Blocipedia", root_path %></li>
    <li><%= link_to "Wikis", wikis_path %></li>
    <li><%= link_to "About", about_path %></li>

    <div class="pull-right user-info">
      <% if user_signed_in? %>
        Welcome&nbsp;<%= link_to current_user.email, user_path(current_user) %>
        <%= link_to "Sign Out", destroy_user_session_path, method: :delete %> 
      <% else %>
        <%= link_to "Sign In", new_user_session_path %> or
        <%= link_to "Sign Up", new_user_registration_path %>
      <% end %>
    </div>
  </ul>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<% if false %> <%= render 'devise/shared/links' %> <% end %>

<%= yield %>
  
</body>
</html>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-8">
    <div class="media">
      <br />
      <% avatar_url = @user.avatar_url(128) %>
      <% if avatar_url %>
        <div class="media-left">
          <%= image_tag avatar_url, class: 'media-object' %>
        </div>
      <% end %>
      <div class="media-body">
        <h2 class="media-heading"><%= @user.email %></h2>
        <% if @user.member? %>
          <h4>Standard User</h4>
        <% elsif @user.premium? %>
          <h4>Premium User</h4>
        <% elsif @user.admin? %>
          <h4>admin</h4>
        <% end %>    
        <small>
          <%= pluralize(@user.wikis.count, 'wiki') %>,
        </small>
      </div>
      <% if current_user.member? %>
        <%= link_to "Upgrade to premium membership", new_charge_path, class: 'btn btn-success' %>
      <% elsif current_user.premium? %>
        <%= link_to "Downgrade to standard membership", user_downgrade_path, method: :put, class: 'btn btn-success', data: { confirm: 'Are you sure you want to downgrade your membership? *Note that all your private wikis will become public after downgrade.' }  %>
      <% end %>
    </div>
  </div>
</div>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome#index-blocipedia</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

app/views/wikis/edit.html.erb
<h1>Wikis#edit</h1>
<%= form_for @wiki do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki name" %>
  </div>

 
  <div class="form-group">
    <%= f.label :body %>
    <div id="epiceditor">
      <%= f.text_area :body, class: 'form-control', placeholder: "Enter wiki description" %>
    </div>
  </div>
  

  <% if (@wiki.user.id == current_user.id && current_user.premium?) || current_user.admin? %>
    <div class="form-group">
      <%= f.label :private, class: 'checkbox' do %>
        <%= f.check_box :private %> Private wiki
      <% end %>
    </div>
  <% end %> 
  <%= f.submit "Save", class: 'wiki-edit-save' %>
<% end %>

  <% if (@wiki.private? && @wiki.user == current_user) || current_user.admin? %>
    <div class="available-users">
      </br>
      <label>Available Users:</label>
        <%= render partial: 'collaborations/add_collaborators', locals: { users: @users } %>
    </div>
    <div class="collaborators">
      </br>
      <label>Collaborators:</label>
        <%= render partial: 'collaborations/collaborators', locals: { wiki: @wiki } %>
    </div>
  <% end %>

<script>
  var editor = new EpicEditor({
    theme: {      
      editor: '<%= asset_path 'editor/epic-light.css' %>',
      preview: '<%= asset_path 'preview/bartik.css' %>'
    }
    , focusOnLoad: true
  }).load(function () {
  console.log("Editor loaded.")});
</script>

app/views/wikis/index.html.erb
<h1>Wikis#index</h1>
<% if current_user.present? %>
  <%= link_to "New Wiki", new_wiki_path %>
<% end %>  
<% @wikis.each do |wiki| %>
  <div class="media">
    <div class="media-body">
      <h4 class="media-heading">               
        <%= link_to wiki.title, wiki %> -Created by&nbsp;<%= wiki.user.email %>
      </h4>
      <small>
        <%= markdown(wiki.body) %>
      </small>  
    </div>
  </div>
<% end %>

app/views/wikis/new.html.erb
<h1>Wikis#new</h1>
<%= form_for @wiki do |f| %>
  <% if @wiki.errors.any? %>
    <div class="alert alert-danger">
      <h4><%= pluralize(@wiki.errors.count, "error") %>.</h4>
      <ul>
        <% @wiki.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <div id="epiceditor">
      <%= f.text_area :body, class: 'form-control', placeholder: "Enter wiki body" %>
    </div>  
  </div>
  <% if current_user.premium? || current_user.admin? %>
    <div class="form-group">
      <%= f.label :private, class: 'checkbox' do %>
        <%= f.check_box :private %> Private wiki
      <% end %>
    </div>
  <% end %>  
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
<% end %>

<script>
  var editor = new EpicEditor({
    theme: {      
      editor: '<%= asset_path 'editor/epic-light.css' %>',
      preview: '<%= asset_path 'preview/bartik.css' %>'
    }
    , focusOnLoad: true
  }).load(function () {
  console.log("Editor loaded.")});
</script>

app/views/wikis/show.html.erb
<h1>Wikis#show</h1>
<% if policy(@wiki).update? %>
  <%= link_to "Edit Wiki", edit_wiki_path, class: 'btn btn-danger' %> 
<% end %>
<% if policy(@wiki).destroy? %>
  <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this wiki?' } %>
<% end %>  
<h3><%= @wiki.title %></h4>
<h5>Author: 
  <% if @wiki.user %>
    <%= @wiki.user.email %>
  <% else %>
    non-user  	
  <% end %>
</h5>
<p><%= markdown(@wiki.body) %></p>

<% if @wiki.private? %>
  <h4>Collaborators:</h4>
  <ul>
    <% @wiki.users.each do |user| %>
     <li><%= user.email %></li>
    <% end %>
  </ul>
<% end %>
    